FROM node:16-alpine3.11

# set working directory
WORKDIR /app

RUN apk update
RUN apk upgrade
RUN apk add git

# install app dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn
# add app
COPY . ./

RUN yarn --cwd src/dependency-manager/

# expose port
# EXPOSE 3000

CMD [ "yarn", "start" ]