FROM node:16-alpine3.11

# set working directory
RUN mkdir -p /usr/src/nuxt-app
WORKDIR /usr/src/nuxt-app

# update and install dependency
RUN apk update && apk upgrade

# add app
COPY . /usr/src/nuxt-app/
RUN yarn

# build necessary, even if no static files are needed,
# since it builds the server as well
RUN yarn build

# expose 5000 on container
# EXPOSE 5000

CMD [ "yarn", "start" ]
